<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemInventoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('item_inventories')->delete();
        
        // \DB::table('item_inventories')->insert(array (
        //     0 => 
        //     array (
        //         'id' => 1,
        //         'categoryInventory_id' => 8,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/050Db2M1H8n3vMQMl21Y.jpg',
        //         'name' => 'Choclo Enlatado 300 g',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-29 18:59:59',
        //         'updated_at' => '2025-05-29 18:59:59',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     1 => 
        //     array (
        //         'id' => 2,
        //         'categoryInventory_id' => 4,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/mEAthLHD4k2FiphglKIN.jpg',
        //         'name' => 'Leche Pil 900 ml',
        //         'dispensingType' => 'Entera',
        //         'observation' => 'Leche entera Pil de 900 ml',
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:19:08',
        //         'updated_at' => '2025-05-30 04:19:08',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     2 => 
        //     array (
        //         'id' => 3,
        //         'categoryInventory_id' => 4,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/JWyWWOSko47YehLMbB9H.jpg',
        //         'name' => 'Mantequilla Pill con sal 100 g',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:21:37',
        //         'updated_at' => '2025-05-30 04:21:37',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     3 => 
        //     array (
        //         'id' => 4,
        //         'categoryInventory_id' => 4,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/TCEyYHhpXQXTlOQyK347.jpg',
        //         'name' => 'Mantequilla Margarina Reyna Pill 850 g',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:23:05',
        //         'updated_at' => '2025-05-30 04:23:05',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     4 => 
        //     array (
        //         'id' => 5,
        //         'categoryInventory_id' => 3,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/398KAN9lCOurxJYAVGgR.jpg',
        //     'name' => 'Cebolla morada (o roja)',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:30:01',
        //         'updated_at' => '2025-05-30 04:30:01',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     5 => 
        //     array (
        //         'id' => 6,
        //         'categoryInventory_id' => 3,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/OFdgdntBKzW2ymjwoMwu.jpg',
        //         'name' => 'Remolacha',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:32:51',
        //         'updated_at' => '2025-05-30 04:32:51',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     6 => 
        //     array (
        //         'id' => 7,
        //         'categoryInventory_id' => 3,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/hoGtrDZWhxFjRhaQhvOk.jpg',
        //         'name' => 'Pepino',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:36:19',
        //         'updated_at' => '2025-05-30 04:36:19',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     7 => 
        //     array (
        //         'id' => 8,
        //         'categoryInventory_id' => 3,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/zItLKx15tPlB2hKGj1TQ.webp',
        //         'name' => 'Papa harinosa',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:38:49',
        //         'updated_at' => '2025-05-30 04:38:49',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     8 => 
        //     array (
        //         'id' => 9,
        //         'categoryInventory_id' => 3,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/jgbHWYLKikqC1yhQ4rXo.webp',
        //         'name' => 'Papa Holandesa',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:39:51',
        //         'updated_at' => '2025-05-30 04:39:51',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     9 => 
        //     array (
        //         'id' => 10,
        //         'categoryInventory_id' => 3,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/yTtODQ1XmMYBm8ZwcXXt.webp',
        //         'name' => 'Zanahoria',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:40:31',
        //         'updated_at' => '2025-05-30 04:40:31',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     10 => 
        //     array (
        //         'id' => 11,
        //         'categoryInventory_id' => 7,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/9DWtYt8khbxXA3xN9yDl.png',
        //         'name' => 'Doña Gusta de Gallina',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:50:12',
        //         'updated_at' => '2025-05-30 04:50:12',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     11 => 
        //     array (
        //         'id' => 12,
        //         'categoryInventory_id' => 7,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/BcoqD321UNdBceiZarew.webp',
        //         'name' => 'Doña Gusta de Carne',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:51:20',
        //         'updated_at' => '2025-05-30 04:51:20',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     12 => 
        //     array (
        //         'id' => 13,
        //         'categoryInventory_id' => 7,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/stO22ndOZe9EJB8itUds.png',
        //         'name' => 'Doña Gusta de Costilla',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:52:52',
        //         'updated_at' => '2025-05-30 04:52:52',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     13 => 
        //     array (
        //         'id' => 14,
        //         'categoryInventory_id' => 6,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/VgZgCvQHfBOkeu2XYz8j.webp',
        //         'name' => 'Sal Yodada de Mesa 1 kg',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:56:09',
        //         'updated_at' => '2025-05-30 04:56:09',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     14 => 
        //     array (
        //         'id' => 15,
        //         'categoryInventory_id' => 6,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/qxaNbi7JP0nPoW8yXpCN.webp',
        //         'name' => 'Canela en Bolsita',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 04:58:30',
        //         'updated_at' => '2025-05-30 04:58:30',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     15 => 
        //     array (
        //         'id' => 16,
        //         'categoryInventory_id' => 6,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/rg6ohuGYKME2Cvb0SAqX.webp',
        //         'name' => 'Pimienta negra molida',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:00:11',
        //         'updated_at' => '2025-05-30 05:00:11',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     16 => 
        //     array (
        //         'id' => 17,
        //         'categoryInventory_id' => 6,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/IvAwagVRRtagaNqzybnB.webp',
        //         'name' => 'Salsa Soya Toscana 460 ml',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:01:41',
        //         'updated_at' => '2025-05-30 05:01:41',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     17 => 
        //     array (
        //         'id' => 18,
        //         'categoryInventory_id' => 1,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/jN2UVkeWIrand9EFWDKE.jpg',
        //         'name' => 'Lomo de Cerdo',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:05:38',
        //         'updated_at' => '2025-05-30 05:05:38',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     18 => 
        //     array (
        //         'id' => 19,
        //         'categoryInventory_id' => 1,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/EzPXYzOFBxpQ2ALcqRB3.webp',
        //         'name' => 'Salchicha Sofia',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:13:30',
        //         'updated_at' => '2025-05-30 05:13:30',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     19 => 
        //     array (
        //         'id' => 20,
        //         'categoryInventory_id' => 1,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/qvykZf845XFkLAGAhuxN.png',
        //         'name' => 'Chuleta de Res',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:15:15',
        //         'updated_at' => '2025-05-30 05:15:46',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     20 => 
        //     array (
        //         'id' => 21,
        //         'categoryInventory_id' => 1,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/w32d2haznMcuBJvX7stX.jpg',
        //         'name' => 'Lomo de Res',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:16:59',
        //         'updated_at' => '2025-05-30 05:16:59',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     21 => 
        //     array (
        //         'id' => 22,
        //         'categoryInventory_id' => 1,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/6nmNQvTej3i5yM99oGVS.jpeg',
        //         'name' => 'Costilla de Res',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:18:04',
        //         'updated_at' => '2025-05-30 05:18:04',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     22 => 
        //     array (
        //         'id' => 23,
        //         'categoryInventory_id' => 1,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/OoZDBukftGebPCyxoYSg.jpg',
        //         'name' => 'Carne Entera de 2da Entera de Res',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:22:14',
        //         'updated_at' => '2025-05-30 05:22:14',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     23 => 
        //     array (
        //         'id' => 24,
        //         'categoryInventory_id' => 1,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/WbYJnUdNIQPcEoX2Tnyb.jpg',
        //         'name' => 'Carne Entera de 1ra Entera de Res',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:23:40',
        //         'updated_at' => '2025-05-30 05:23:40',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     24 => 
        //     array (
        //         'id' => 25,
        //         'categoryInventory_id' => 1,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/QhJZHKWu2qWrp3fa5Ey4.webp',
        //         'name' => 'Pechuga de Pollo',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:24:59',
        //         'updated_at' => '2025-05-30 05:24:59',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     25 => 
        //     array (
        //         'id' => 26,
        //         'categoryInventory_id' => 1,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/nHqKi7Q5ZKXumCTrvtW2.webp',
        //         'name' => 'Alitas de Pollo',
        //         'dispensingType' => 'Fraccionaria',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:26:04',
        //         'updated_at' => '2025-05-30 05:26:04',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     26 => 
        //     array (
        //         'id' => 27,
        //         'categoryInventory_id' => 5,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/pMWbn4IHKfGkDccHORxP.webp',
        //         'name' => 'Aceite Fino Vegetal',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:27:42',
        //         'updated_at' => '2025-05-30 05:27:42',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     27 => 
        //     array (
        //         'id' => 28,
        //         'categoryInventory_id' => 6,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/5th6l3zkBOlwfhv6EttJ.webp',
        //         'name' => 'Mayoneza Kris 230 g',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:29:31',
        //         'updated_at' => '2025-05-30 05:29:31',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     28 => 
        //     array (
        //         'id' => 29,
        //         'categoryInventory_id' => 6,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/O26XHqUUiXtR3BWsJard.jpg',
        //         'name' => 'Mostaza Kris 200 g',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:30:17',
        //         'updated_at' => '2025-05-30 05:30:17',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     29 => 
        //     array (
        //         'id' => 30,
        //         'categoryInventory_id' => 6,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/tT1t1beJ0Zl372ivWHOe.webp',
        //         'name' => 'Ketchup kris 200 g',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:31:08',
        //         'updated_at' => '2025-05-30 05:31:08',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     30 => 
        //     array (
        //         'id' => 31,
        //         'categoryInventory_id' => 6,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/qaVHFyklmPRlSAvV4aXM.webp',
        //         'name' => 'Mayoneza Ahumada Kris 200 g',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:32:35',
        //         'updated_at' => '2025-05-30 05:32:35',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     31 => 
        //     array (
        //         'id' => 32,
        //         'categoryInventory_id' => 6,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/OZ9luXFLrqjwHtneYqE1.webp',
        //         'name' => 'Vainilla Miki 110 ml',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:37:27',
        //         'updated_at' => '2025-05-30 05:37:47',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     32 => 
        //     array (
        //         'id' => 33,
        //         'categoryInventory_id' => 6,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/wb5YKrorArtQG1h1jwlJ.jpg',
        //         'name' => 'Vinagre Toscano Tinto 750 ml',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:42:08',
        //         'updated_at' => '2025-05-30 05:42:08',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     33 => 
        //     array (
        //         'id' => 34,
        //         'categoryInventory_id' => 11,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/WnoqOuiSteczYCe8RABO.webp',
        //         'name' => 'Detergente en Polvo UNO 800 gr',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:44:24',
        //         'updated_at' => '2025-05-30 05:44:24',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     34 => 
        //     array (
        //         'id' => 35,
        //         'categoryInventory_id' => 11,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/w43630JhDdSCdpjvcE6f.webp',
        //         'name' => 'Ola Lavavajilla 1.05 l',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:47:23',
        //         'updated_at' => '2025-05-30 05:47:23',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     35 => 
        //     array (
        //         'id' => 36,
        //         'categoryInventory_id' => 11,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/oL4oqW4rY2tvUEfQO2gv.webp',
        //         'name' => 'Lavandina X-5 1 L',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:48:52',
        //         'updated_at' => '2025-05-30 05:48:52',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     36 => 
        //     array (
        //         'id' => 37,
        //         'categoryInventory_id' => 12,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/dmmRDyre9LAbhmUbCGSO.webp',
        //         'name' => 'Esponja Lavavajilla',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:52:35',
        //         'updated_at' => '2025-05-30 05:52:35',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     37 => 
        //     array (
        //         'id' => 38,
        //         'categoryInventory_id' => 12,
        //         'unitType_id' => NULL,
        //         'image' => NULL,
        //         'name' => 'Bombril Girasol',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:55:04',
        //         'updated_at' => '2025-05-30 05:55:04',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     38 => 
        //     array (
        //         'id' => 39,
        //         'categoryInventory_id' => 12,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/fbNi6oje0Nep61hf1Vc1.webp',
        //         'name' => 'Escobas',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:55:52',
        //         'updated_at' => '2025-05-30 05:55:52',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     39 => 
        //     array (
        //         'id' => 40,
        //         'categoryInventory_id' => 12,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/tDaOeAmvhHrz5GAMGgiw.jpg',
        //         'name' => 'Trapeador',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:56:41',
        //         'updated_at' => '2025-05-30 05:56:41',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     40 => 
        //     array (
        //         'id' => 41,
        //         'categoryInventory_id' => 13,
        //         'unitType_id' => NULL,
        //         'image' => 'item-inventories/May2025/36HOCeXYsydUCJ194QvC.webp',
        //         'name' => 'Baygon Verde 300 ml',
        //         'dispensingType' => 'Entera',
        //         'observation' => NULL,
        //         'status' => 1,
        //         'created_at' => '2025-05-30 05:59:17',
        //         'updated_at' => '2025-05-30 05:59:17',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        // ));
        
        
    }
}