<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemSalesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('item_sales')->delete();
        
        // \DB::table('item_sales')->insert(array (
        //     0 => 
        //     array (
        //         'id' => 1,
        //         'category_id' => 1,
        //         'image' => 'item-sales/May2025/Xl40uVtVbv7C2xTuJ9uF.webp',
        //         'name' => 'Coca Cola 2 Litro',
        //         'price' => '13.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Con Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 08:51:02',
        //         'updated_at' => '2025-05-27 08:52:16',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     1 => 
        //     array (
        //         'id' => 2,
        //         'category_id' => 1,
        //         'image' => 'item-sales/May2025/qlAuA8syofE10G9qIDXN.webp',
        //         'name' => 'Coca Cola 3 Litro',
        //         'price' => '17.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Con Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 08:51:23',
        //         'updated_at' => '2025-05-27 08:51:23',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     2 => 
        //     array (
        //         'id' => 3,
        //         'category_id' => 1,
        //         'image' => 'item-sales/May2025/7opjp5dCxjhEbmaOGuBE.webp',
        //         'name' => 'Fanta 3 Lt',
        //         'price' => '17.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Con Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 10:30:00',
        //         'updated_at' => '2025-05-27 10:30:00',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     3 => 
        //     array (
        //         'id' => 4,
        //         'category_id' => 1,
        //         'image' => 'item-sales/May2025/8Pm5UkAZw3j6VFB6xfaM.jpg',
        //         'name' => 'Sprite 2 Ltro',
        //         'price' => '13.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Con Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 10:30:54',
        //         'updated_at' => '2025-05-27 10:30:54',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     4 => 
        //     array (
        //         'id' => 5,
        //         'category_id' => 1,
        //         'image' => 'item-sales/May2025/U3oGFkxkx6ghZLIt9YHD.webp',
        //         'name' => 'Pepsi 500 ml',
        //         'price' => '8.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Con Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 10:32:37',
        //         'updated_at' => '2025-05-27 10:32:37',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     5 => 
        //     array (
        //         'id' => 6,
        //         'category_id' => 1,
        //         'image' => 'item-sales/May2025/DvRZ3nkYFV2RWIs2xW8G.jpg',
        //         'name' => 'Coca cola 330 ml',
        //         'price' => '8.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Con Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 10:33:52',
        //         'updated_at' => '2025-05-27 10:33:52',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     6 => 
        //     array (
        //         'id' => 7,
        //         'category_id' => 1,
        //         'image' => 'item-sales/May2025/BqKwWiFVPrfv5Fegj3fQ.webp',
        //         'name' => 'Powerade 500 ml',
        //         'price' => '12.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Con Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 10:34:53',
        //         'updated_at' => '2025-05-27 10:34:53',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     7 => 
        //     array (
        //         'id' => 8,
        //         'category_id' => 2,
        //         'image' => 'item-sales/May2025/D2GgoKm1Gjamq6sGlp7a.jpeg',
        //         'name' => 'Lomo',
        //         'price' => '16.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 10:50:52',
        //         'updated_at' => '2025-05-27 10:50:52',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     8 => 
        //     array (
        //         'id' => 9,
        //         'category_id' => 2,
        //         'image' => 'item-sales/May2025/TsIxM8z1OXU9dkWNzDGJ.jpg',
        //         'name' => 'Pipocas de Pollo',
        //         'price' => '18.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Con Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 11:30:08',
        //         'updated_at' => '2025-05-29 07:08:41',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     9 => 
        //     array (
        //         'id' => 10,
        //         'category_id' => 2,
        //         'image' => 'item-sales/May2025/2kMYtxBKO0rVZvFGooYJ.jpg',
        //         'name' => 'Salchipapas',
        //         'price' => '13.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 11:34:02',
        //         'updated_at' => '2025-05-27 11:34:02',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     10 => 
        //     array (
        //         'id' => 11,
        //         'category_id' => 2,
        //         'image' => 'item-sales/May2025/CRMdSzmWpsqOzTU1zVKa.jpg',
        //         'name' => 'Sandwich de Lomito',
        //         'price' => '25.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 11:35:08',
        //         'updated_at' => '2025-05-27 11:35:08',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     11 => 
        //     array (
        //         'id' => 12,
        //         'category_id' => 2,
        //         'image' => 'item-sales/May2025/9y6jIQa7XHLVBhV4j03l.jpg',
        //         'name' => 'Hamburguesa',
        //         'price' => '16.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 11:36:04',
        //         'updated_at' => '2025-05-27 11:36:04',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     12 => 
        //     array (
        //         'id' => 13,
        //         'category_id' => 2,
        //         'image' => 'item-sales/May2025/o0M0F6rtNf4DvWvFeuhh.jpg',
        //         'name' => 'Keperi',
        //         'price' => '18.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 11:37:13',
        //         'updated_at' => '2025-05-27 11:37:13',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     13 => 
        //     array (
        //         'id' => 14,
        //         'category_id' => 2,
        //         'image' => 'item-sales/May2025/lKcAfnAY4CLH9CzxlXZo.jpg',
        //         'name' => 'Charque',
        //         'price' => '18.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 11:38:33',
        //         'updated_at' => '2025-05-27 11:38:33',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     14 => 
        //     array (
        //         'id' => 15,
        //         'category_id' => 2,
        //         'image' => 'item-sales/May2025/zaOxi2pGLOSJ5jc1UCk2.webp',
        //         'name' => 'Pique Macho',
        //         'price' => '25.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 11:39:54',
        //         'updated_at' => '2025-05-27 11:39:54',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     15 => 
        //     array (
        //         'id' => 16,
        //         'category_id' => 2,
        //         'image' => 'item-sales/May2025/hvpHO41IoVJFcHnMlu0t.jpg',
        //         'name' => 'Lomito Saltado',
        //         'price' => '25.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 11:40:47',
        //         'updated_at' => '2025-05-27 11:40:47',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     16 => 
        //     array (
        //         'id' => 17,
        //         'category_id' => 4,
        //         'image' => 'item-sales/May2025/YAxsK0mdH1KsiXHg2FbI.jpg',
        //         'name' => 'Torta tres Leche',
        //         'price' => '12.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 11:42:12',
        //         'updated_at' => '2025-05-27 11:42:12',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     17 => 
        //     array (
        //         'id' => 18,
        //         'category_id' => 5,
        //         'image' => 'item-sales/May2025/xJtTvHpgLn0cNlYqsBPH.jpg',
        //         'name' => 'Papas Fritas',
        //         'price' => '6.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 11:43:19',
        //         'updated_at' => '2025-05-27 11:43:19',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     18 => 
        //     array (
        //         'id' => 19,
        //         'category_id' => 5,
        //         'image' => 'item-sales/May2025/9i2mtIjaQaLFAHkUTPhS.jpg',
        //         'name' => 'Arroz',
        //         'price' => '6.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 11:44:13',
        //         'updated_at' => '2025-05-27 11:44:13',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     19 => 
        //     array (
        //         'id' => 20,
        //         'category_id' => 5,
        //         'image' => 'item-sales/May2025/iXDtuWuhwD9IPmzq9yq2.jpg',
        //         'name' => 'Platanos Maduro',
        //         'price' => '6.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-27 11:47:14',
        //         'updated_at' => '2025-05-27 11:47:14',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     20 => 
        //     array (
        //         'id' => 21,
        //         'category_id' => 3,
        //         'image' => 'item-sales/May2025/CxMxVNtuwdDpukgpidwh.jpg',
        //         'name' => 'ENSALADA RUSA',
        //         'price' => '5.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Sin Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-28 04:52:36',
        //         'updated_at' => '2025-05-28 04:52:36',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     21 => 
        //     array (
        //         'id' => 22,
        //         'category_id' => 1,
        //         'image' => 'item-sales/May2025/DJwQVILSjg716tbdHlT6.webp',
        //         'name' => 'Guarana 2 ltro',
        //         'price' => '12.00',
        //         'observation' => NULL,
        //         'typeSale' => 'Venta Con Stock',
        //         'status' => 1,
        //         'created_at' => '2025-05-28 07:32:16',
        //         'updated_at' => '2025-05-28 07:32:16',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        // ));
        
        
    }
}