<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemInventoryStocksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('item_inventory_stocks')->delete();
        
        // \DB::table('item_inventory_stocks')->insert(array (
        //     0 => 
        //     array (
        //         'id' => 1,
        //         'itemInventory_id' => 40,
        //         'quantity' => '1.00',
        //         'stock' => '1.00',
        //         'type' => 'Ingreso',
        //         'observation' => 'Compra de un rapeador',
        //         'created_at' => '2025-05-30 10:41:16',
        //         'updated_at' => '2025-06-02 11:30:01',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     1 => 
        //     array (
        //         'id' => 2,
        //         'itemInventory_id' => 37,
        //         'quantity' => '6.00',
        //         'stock' => '6.00',
        //         'type' => 'Ingreso',
        //         'observation' => 'Campra de un paquete de esponja con 6 unidades',
        //         'created_at' => '2025-05-30 10:41:55',
        //         'updated_at' => '2025-06-02 11:35:27',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     2 => 
        //     array (
        //         'id' => 3,
        //         'itemInventory_id' => 36,
        //         'quantity' => '6.00',
        //         'stock' => '6.00',
        //         'type' => 'Ingreso',
        //         'observation' => 'Compra de una caja de lavandina',
        //         'created_at' => '2025-05-30 10:42:41',
        //         'updated_at' => '2025-05-30 10:42:41',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     3 => 
        //     array (
        //         'id' => 4,
        //         'itemInventory_id' => 26,
        //         'quantity' => '10.00',
        //         'stock' => '10.00',
        //         'type' => 'Ingreso',
        //         'observation' => '10 kilos de alitas de pollo',
        //         'created_at' => '2025-05-30 10:43:22',
        //         'updated_at' => '2025-05-30 10:43:22',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     4 => 
        //     array (
        //         'id' => 5,
        //         'itemInventory_id' => 25,
        //         'quantity' => '5.00',
        //         'stock' => '5.00',
        //         'type' => 'Ingreso',
        //         'observation' => '5 kilo de pechuga de pollo para pipocas',
        //         'created_at' => '2025-05-30 10:43:59',
        //         'updated_at' => '2025-05-30 10:43:59',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     5 => 
        //     array (
        //         'id' => 6,
        //         'itemInventory_id' => 24,
        //         'quantity' => '8.00',
        //         'stock' => '8.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:44:17',
        //         'updated_at' => '2025-06-02 11:35:27',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     6 => 
        //     array (
        //         'id' => 7,
        //         'itemInventory_id' => 23,
        //         'quantity' => '3.00',
        //         'stock' => '3.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:44:35',
        //         'updated_at' => '2025-05-30 10:44:35',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     7 => 
        //     array (
        //         'id' => 8,
        //         'itemInventory_id' => 21,
        //         'quantity' => '15.00',
        //         'stock' => '15.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:45:51',
        //         'updated_at' => '2025-05-30 10:45:51',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     8 => 
        //     array (
        //         'id' => 9,
        //         'itemInventory_id' => 21,
        //         'quantity' => '2.00',
        //         'stock' => '2.00',
        //         'type' => 'Ingreso',
        //         'observation' => 'nueva compra',
        //         'created_at' => '2025-05-30 10:46:10',
        //         'updated_at' => '2025-05-30 10:46:10',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     9 => 
        //     array (
        //         'id' => 10,
        //         'itemInventory_id' => 19,
        //         'quantity' => '10.00',
        //         'stock' => '10.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:46:31',
        //         'updated_at' => '2025-05-30 10:46:31',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     10 => 
        //     array (
        //         'id' => 11,
        //         'itemInventory_id' => 10,
        //         'quantity' => '4.00',
        //         'stock' => '4.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:47:04',
        //         'updated_at' => '2025-05-30 10:47:04',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     11 => 
        //     array (
        //         'id' => 12,
        //         'itemInventory_id' => 8,
        //         'quantity' => '11.00',
        //         'stock' => '11.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:47:33',
        //         'updated_at' => '2025-05-30 10:47:33',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     12 => 
        //     array (
        //         'id' => 13,
        //         'itemInventory_id' => 7,
        //         'quantity' => '5.00',
        //         'stock' => '5.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:48:36',
        //         'updated_at' => '2025-05-30 10:48:36',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     13 => 
        //     array (
        //         'id' => 14,
        //         'itemInventory_id' => 5,
        //         'quantity' => '6.00',
        //         'stock' => '6.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:48:58',
        //         'updated_at' => '2025-05-30 10:48:58',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     14 => 
        //     array (
        //         'id' => 15,
        //         'itemInventory_id' => 2,
        //         'quantity' => '5.00',
        //         'stock' => '5.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:49:38',
        //         'updated_at' => '2025-05-30 10:49:38',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     15 => 
        //     array (
        //         'id' => 16,
        //         'itemInventory_id' => 27,
        //         'quantity' => '12.00',
        //         'stock' => '12.00',
        //         'type' => 'Ingreso',
        //         'observation' => 'Compra de aceite en caja con 12 unidades',
        //         'created_at' => '2025-05-30 10:50:35',
        //         'updated_at' => '2025-05-30 10:50:35',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     16 => 
        //     array (
        //         'id' => 17,
        //         'itemInventory_id' => 14,
        //         'quantity' => '4.00',
        //         'stock' => '4.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:51:04',
        //         'updated_at' => '2025-05-30 10:51:04',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     17 => 
        //     array (
        //         'id' => 18,
        //         'itemInventory_id' => 33,
        //         'quantity' => '5.00',
        //         'stock' => '5.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:52:34',
        //         'updated_at' => '2025-05-30 10:52:34',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     18 => 
        //     array (
        //         'id' => 19,
        //         'itemInventory_id' => 33,
        //         'quantity' => '2.00',
        //         'stock' => '2.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:52:39',
        //         'updated_at' => '2025-05-30 10:52:39',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     19 => 
        //     array (
        //         'id' => 20,
        //         'itemInventory_id' => 11,
        //         'quantity' => '50.00',
        //         'stock' => '50.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:53:03',
        //         'updated_at' => '2025-05-30 10:53:03',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     20 => 
        //     array (
        //         'id' => 21,
        //         'itemInventory_id' => 12,
        //         'quantity' => '60.00',
        //         'stock' => '60.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:53:18',
        //         'updated_at' => '2025-06-02 11:35:27',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     21 => 
        //     array (
        //         'id' => 22,
        //         'itemInventory_id' => 13,
        //         'quantity' => '30.00',
        //         'stock' => '30.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:53:33',
        //         'updated_at' => '2025-05-30 10:53:33',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     22 => 
        //     array (
        //         'id' => 23,
        //         'itemInventory_id' => 41,
        //         'quantity' => '2.00',
        //         'stock' => '2.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:54:35',
        //         'updated_at' => '2025-05-30 10:54:35',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     23 => 
        //     array (
        //         'id' => 24,
        //         'itemInventory_id' => 34,
        //         'quantity' => '5.00',
        //         'stock' => '5.00',
        //         'type' => 'Ingreso',
        //         'observation' => 'compra',
        //         'created_at' => '2025-05-30 10:54:56',
        //         'updated_at' => '2025-05-30 10:54:56',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     24 => 
        //     array (
        //         'id' => 25,
        //         'itemInventory_id' => 1,
        //         'quantity' => '5.00',
        //         'stock' => '5.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-05-30 10:55:14',
        //         'updated_at' => '2025-05-30 10:55:14',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        //     25 => 
        //     array (
        //         'id' => 26,
        //         'itemInventory_id' => 1,
        //         'quantity' => '2.00',
        //         'stock' => '2.00',
        //         'type' => 'Ingreso',
        //         'observation' => NULL,
        //         'created_at' => '2025-06-04 07:18:04',
        //         'updated_at' => '2025-06-04 07:18:04',
        //         'registerUser_id' => 1,
        //         'registerRole' => 'admin',
        //         'deleted_at' => NULL,
        //         'deleteUser_id' => NULL,
        //         'deleteRole' => NULL,
        //         'deleteObservation' => NULL,
        //     ),
        // ));
        
        
    }
}