<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Inicio',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-house',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2024-10-18 08:31:13',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2024-10-18 08:40:50',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Usuarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 1,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2024-10-18 08:33:38',
                'route' => 'voyager.users.index',
                'parameters' => 'null',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 14,
                'order' => 2,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2024-10-18 08:33:29',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Herramientas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2025-10-06 19:57:58',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2024-10-18 08:33:17',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2024-10-18 08:40:50',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2024-10-18 08:40:50',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2024-10-18 08:40:50',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Configuración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2025-10-06 19:57:58',
                'route' => 'voyager.settings.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Seguridad',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-lock',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2024-10-18 08:33:05',
                'updated_at' => '2025-10-06 19:57:58',
                'route' => NULL,
                'parameters' => '',
            ),
            11 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Limpiar cache',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-broom',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2024-12-09 04:33:25',
                'updated_at' => '2025-10-06 19:57:58',
                'route' => 'clear.cache',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Administración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-regular fa-folder-open',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2025-02-10 07:42:49',
                'updated_at' => '2025-10-06 19:57:58',
                'route' => NULL,
                'parameters' => '',
            ),
            13 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Personas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-person',
                'color' => NULL,
                'parent_id' => 16,
                'order' => 1,
                'created_at' => '2025-04-07 01:43:00',
                'updated_at' => '2025-04-07 01:44:30',
                'route' => 'voyager.people.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Categorías',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-layer-group',
                'color' => NULL,
                'parent_id' => 20,
                'order' => 1,
                'created_at' => '2025-05-26 10:01:28',
                'updated_at' => '2025-05-26 10:10:42',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Parámetro de Ventas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-params',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2025-05-26 10:10:27',
                'updated_at' => '2025-10-06 19:57:58',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Productos en Ventas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => NULL,
                'parent_id' => 20,
                'order' => 2,
                'created_at' => '2025-05-26 10:20:09',
                'updated_at' => '2025-05-26 14:25:16',
                'route' => 'voyager.item-sales.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Ventas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cart-shopping',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2025-05-27 08:58:33',
                'updated_at' => '2025-10-06 19:57:58',
                'route' => 'sales.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Parámetro del Almacén',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-params',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2025-05-29 09:28:39',
                'updated_at' => '2025-10-06 19:57:58',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Categorías del Almacén',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-layer-group',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 1,
                'created_at' => '2025-05-29 09:34:21',
                'updated_at' => '2025-06-02 07:38:54',
                'route' => 'voyager.category-inventories.index',
                'parameters' => 'null',
            ),
            20 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Productos del Almacén',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => NULL,
                'parent_id' => 24,
                'order' => 2,
                'created_at' => '2025-05-29 13:21:40',
                'updated_at' => '2025-06-02 07:38:54',
                'route' => 'voyager.item-inventories.index',
                'parameters' => NULL,
            ),
            21 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Egresos del Almacen',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cart-shopping',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2025-06-02 07:38:47',
                'updated_at' => '2025-10-06 19:57:58',
                'route' => 'egres-inventories.index',
                'parameters' => NULL,
            ),
            22 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'Reportes de Ventas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2025-06-02 12:00:55',
                'updated_at' => '2025-10-06 19:57:58',
                'route' => NULL,
                'parameters' => '',
            ),
            23 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Stock Disponible',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 29,
                'order' => 2,
                'created_at' => '2025-06-02 17:57:33',
                'updated_at' => '2025-06-12 04:36:15',
                'route' => 'report-sales-stock.index',
                'parameters' => 'null',
            ),
            24 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Ventas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 29,
                'order' => 1,
                'created_at' => '2025-06-02 19:47:24',
                'updated_at' => '2025-06-12 04:35:54',
                'route' => 'report-sales.index',
                'parameters' => 'null',
            ),
            25 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Ingresos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 29,
                'order' => 3,
                'created_at' => '2025-06-04 05:15:31',
                'updated_at' => '2025-06-12 04:36:41',
                'route' => 'report-sales-income.index',
                'parameters' => 'null',
            ),
            26 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Reportes del Almacen',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2025-06-04 06:18:07',
                'updated_at' => '2025-10-06 19:57:58',
                'route' => NULL,
                'parameters' => '',
            ),
            27 => 
            array (
                'id' => 34,
                'menu_id' => 1,
                'title' => 'Ingresos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 33,
                'order' => 3,
                'created_at' => '2025-06-04 06:19:31',
                'updated_at' => '2025-06-12 04:44:49',
                'route' => 'report-inventories-income.index',
                'parameters' => 'null',
            ),
            28 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'Stock Disponible',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 33,
                'order' => 2,
                'created_at' => '2025-06-04 06:47:02',
                'updated_at' => '2025-06-12 04:44:32',
                'route' => 'report-inventories-stock.index',
                'parameters' => 'null',
            ),
            29 => 
            array (
                'id' => 36,
                'menu_id' => 1,
                'title' => 'Salidas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 33,
                'order' => 1,
                'created_at' => '2025-06-04 07:39:31',
                'updated_at' => '2025-06-12 04:44:20',
                'route' => 'report-inventories-egres.index',
                'parameters' => 'null',
            ),
            30 => 
            array (
                'id' => 37,
                'menu_id' => 1,
                'title' => 'Bóveda',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-vault',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2025-10-06 15:58:51',
                'updated_at' => '2025-10-06 15:58:58',
                'route' => 'vaults.index',
                'parameters' => NULL,
            ),
            31 => 
            array (
                'id' => 38,
                'menu_id' => 1,
                'title' => 'Cajeros',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cash-register',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2025-10-06 19:57:47',
                'updated_at' => '2025-10-06 19:57:58',
                'route' => 'cashiers.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}